M48
; DRILL file KiCad 10.0.4 date 2026-07-14T22:28:03
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-14T22:28:03-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X27.11Y-123.4
X32.89Y-123.4
T2
X103.46Y-85.66
X108.54Y-14.34
M30
